#include "vmath.h"
#include <math.h>

//---------------------------------------------------------------------------//
// function definitions for each type
//---------------------------------------------------------------------------//
VEC_ADD(u8)
VEC_ADD(i32)
VEC_ADD(f)
VEC_SUB(u8)
VEC_SUB(i32)
VEC_SUB(f)
VEC_MUL(u8)
VEC_MUL(i32)
VEC_MUL(f)
VEC_DIV(f)
VEC_DIV(u8)
VEC_DIV(i32)
VEC_DOT(f)
VEC_DOT(u8)
VEC_DOT(i32)
VEC_SCMUL(f)
VEC_SCMUL(u8)
VEC_SCMUL(i32)
VEC_NORMSQ(f)
VEC_NORMSQ(u8)
VEC_NORMSQ(i32)
VEC_NORM(f)
VEC_NORM(u8)
VEC_NORM(i32)
VEC_UNIT(f)
VEC_UNIT(u8)
VEC_UNIT(i32)
VEC_COS(f)
VEC_COS(u8)
VEC_COS(i32)
VEC_ANGLE(f)
VEC_ANGLE(u8)
VEC_ANGLE(i32)
